### ISSUE TITLE
Correction for README.md

### ISSUE THREAD

**Issue by awktane** [Heroes-Profile/heroesprofile#1003]
Quite an easy one really... "This public repository is the site re-write for Heroes Profile and is not currently in production."

I believe it is now in production. 😄

**Comment by Zemill** [comment]
Part of why we made the site public like this was in the hopes users would take it upon themselves to actually create their own solutions to issues or ideas they have.

This is a perfect example of something that could be handled by the community and a pull request made

Like so

https://github.com/Heroes-Profile/heroesprofile/pull/1004


With that said, I do appreciate the feedback, thank you
