### ISSUE TITLE
Can't click to filter Global Hero  Stats

### ISSUE THREAD

**Issue by KarmilApple** [Heroes-Profile/heroesprofile#1015]
**Describe the bug**
When I try to click on filter options for global hero statistics: Timeframe, Game type, etc. it redirects to the ad behind it all, the Homeworld 3 ad, and the filters don't work

**To Reproduce**
1. Go to Global Hero Stats
2. Click on any filter
3. See error

**Expected behavior**
The fliter options should pop up

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by Zemill** [comment]
I am fixing this now

**Comment by Zemill** [comment]
I think this is fixed now, please verify
