### ISSUE TITLE
Feature request: add battletag in UI for people you've played with

### ISSUE THREAD

**Issue by nightblade9** [Heroes-Profile/heroesprofile#1102]
Use case: looking for some friends from previous matches who are no longer in my friend list. I can see their user names in the match history details, but I need their full battletag in order to search and add them to my friends list.

Request: please add battletags to the match history, next to each user's name. Or, honestly, anywhere else where I can satisfy my use case and find someone's battle tag.

Fake screenshot below, see red text. 

![image](https://github.com/user-attachments/assets/6b7be42f-3a4a-4ffb-b672-6b1520baac78)

**Comment by Zemill** [comment]
This was a conscious decision we made when the website was created to protect users privacy, as much as we can.  It is not something we are planning to change
