### ISSUE TITLE
Drag-able columns.  Let users change order of columns

### ISSUE THREAD

**Issue by lifeinabstract** [Heroes-Profile/heroesprofile#49]
Example code at 
https://github.com/SortableJS/Vue.Draggable/blob/master/example/components/table-column-example.vue

**Comment by MGatner** [comment]
I use SortableJS in a project and I’m very pleased with it. I haven’t tried the Vue extensions but I imagine it’s great quality.

**Comment by Zemill** [comment]
implemented
