### ISSUE TITLE
Leaderboard page not working

### ISSUE THREAD

**Issue by timkovik** [Heroes-Profile/heroesprofile#552]
**Describe the bug**
https://rewrite.heroesprofile.com/Global/Leaderboard show error message.

Endpoint https://rewrite.heroesprofile.com/Global/Leaderboard return error 500

**To Reproduce**
1. Go to 'https://rewrite.heroesprofile.com/Global/Leaderboard'

**Expected behavior**
Leaderboard loaded

**Comment by Zemill** [comment]
What device are you using?  I just tried it out and data loaded

**Comment by Zemill** [comment]
> Oh, I find it broken some times on all pages. Looks like backend tired :C
> 
> Or is it because I'm from Russia.

See #557


Did you log in to the site?

**Comment by timkovik** [comment]
> > Oh, I find it broken some times on all pages. Looks like backend tired :C
> > Or is it because I'm from Russia.
> 
> See #557
> 
> Did you log in to the site?

Ye, I was logged in
