### ISSUE TITLE
Server error 500 inconsistently across site.

### ISSUE THREAD

**Issue by Zemill** [Heroes-Profile/heroesprofile#557]
I need to fix the logging.  I am getting the logs that there are server errors, but its not logging what the error is.

**Comment by Zemill** [comment]
I never got this error during my testing, but users are reporting it happening in firefox but when they switch to chrome it doesnt occur.  So there is some variance occuring

**Comment by Techn0core** [comment]
I can reproduce a 500 error by logging in, and then going to any URL inside /Global. I can stop getting 500 errors by logging out.

**Comment by Techn0core** [comment]
> @Techn0core I have implemented a different logging solution, so if you have time, could you repeat what caused the errors so I can investigate further,
> 
> Thanks

Sure! I just browsed around while logged in, I see the new error page.

**Comment by Zemill** [comment]
> > @Techn0core I have implemented a different logging solution, so if you have time, could you repeat what caused the errors so I can investigate further,
> > Thanks
> 
> Sure! I just browsed around while logged in, I see the new error page.

Thanks, I see where the error is coming from now, should be fixed when I get out of my meetings in a few hours
