### ISSUE TITLE
Site Settings are not being saved

### ISSUE THREAD

**Issue by Dennisenzo** [Heroes-Profile/heroesprofile#578]
**Describe the bug**
The site settings don't seem to be saved anywhere. There's no save button and both 'default game type' and 'advanced fitering' just reset to their default values after reloading the page.

**To Reproduce**
1. Go to 'https://rewrite.heroesprofile.com/Profile/Settings'
2. Change any of the site settings
3. Reload the page
4. The settings are back to their default values

**Expected behavior**
I'd expect these settings to be saved, either automatically or by a save button.

**Screenshots**
![image](https://github.com/Heroes-Profile/heroesprofile/assets/5540269/6e889c1e-075a-4902-83b8-f08b63ed7852)

**Comment by Zemill** [comment]
Ah you are right, this is an oversight on my part.  The designer wanted to remove the save button so I told her to go ahead and do it and I would come back and change these two settings to save on change, and forgot to do that.

This will be the next thing I fix, 

Thanks
