### ISSUE TITLE
(Rewrite site) One teams advanced stats shown for both teams 

### ISSUE THREAD

**Issue by matt2802** [Heroes-Profile/heroesprofile#622]
**Describe the bug**
When viewing the advanced stats of a match, the advanced stats for team 2 are shown instead of the team 1 stats. This can also happen in the opposite - i.e team 1s stats are shown for both teams.
This affects the rewrite site and not the original

**To Reproduce**
1. Ensure you are using the rewrite site
2. Navigate to a players profile
3. Click on a match from match history
4. Scroll down to team 1 advanced stats, note the values
5. Scroll down to team 2 advanced stats, and see the values are the same as the team 1 values 

**Expected behaviour**
When I view a teams advanced stats, I see the correct stats for the players on the team

**Screenshots**
Example game, id = 51419125
![image](https://github.com/Heroes-Profile/heroesprofile/assets/37634494/31a7ab14-7bbd-4eac-94e3-bf61e841a52c)
![image](https://github.com/Heroes-Profile/heroesprofile/assets/37634494/1b75149a-e4f1-44df-a4f2-6c5d2e00b7e8)
note the same stats columns are shown for both teams

![image](https://github.com/Heroes-Profile/heroesprofile/assets/37634494/e437afc6-3704-45c3-9d56-4a0ed80c0d96)
By checking the scoreboard you can see the team 2 stats have been used for both teams.

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - 120.0.6099.130

**Additional context**
N/A

**Comment by Zemill** [comment]
Should be fixed in the recent release
