### ISSUE TITLE
Finalize ad implementation - SPA and ad-block container

### ISSUE THREAD

**Issue by Zemill** [Heroes-Profile/heroesprofile#649]
Need to implement ads for SPA pages and then create a container for ads to sit in with default data for users with ad-blockers showing info about why we have ads etc etc

**Comment by Zemill** [comment]
I added the ad block functionality, just need to style it.  Its in the header.  Just run adblock for it to show up

![image](https://github.com/Heroes-Profile/heroesprofile/assets/33404722/f9011fae-c62d-4fbe-8fe2-1a4c3deaeb3e)

**Comment by Zemill** [comment]
https://github.com/Heroes-Profile/heroesprofile/blob/760cf76edec673c318be42ff2c5dcedefbdc8274/resources/js/components/Ads/HorizontalBannerAd.vue#L3

**Comment by lifeinabstract** [comment]
I styled the message at the top of the page; was there something else I needed to do for ads on this?

**Comment by Zemill** [comment]
Yes the SPA stuff is different.  Need to check our emails from ad provider on how that is set up
