### ISSUE TITLE
Privacy policy link and styling

### ISSUE THREAD

**Issue by Zemill** [Heroes-Profile/heroesprofile#658]
Add privacy policy link somewhere on the site and then also style the privacy policy page

https://rewrite.heroesprofile.com/Privacy/Policy

**Comment by lifeinabstract** [comment]
Updated styling on the page but do we have this cookies popup? 
![image](https://github.com/Heroes-Profile/heroesprofile/assets/11604308/bb8f10a2-04f1-4bdb-b3b3-5cd4fc4ad367)

**Comment by Zemill** [comment]
No I haven't added it yet
