### ISSUE TITLE
Cookies Popup

### ISSUE THREAD

**Issue by lifeinabstract** [Heroes-Profile/heroesprofile#688]
![image](https://github.com/Heroes-Profile/heroesprofile/assets/11604308/5690fe9a-7ada-4fe4-89e1-ad3903a8e0c9)

**Comment by Zemill** [comment]
I have added the architecture for this

The Vue component is called at
https://github.com/Heroes-Profile/heroesprofile/blob/ecb2a478b4daea2bbed2a72ffb084fb53220ac9b/resources/views/layouts/app.blade.php#L94

The vue component itself is
https://github.com/Heroes-Profile/heroesprofile/blob/develop/resources/js/components/FooterPopupDisclaimer.vue


Need to style that along with style the privacy policy per #658 
https://github.com/Heroes-Profile/heroesprofile/issues/658
