### ISSUE TITLE
Match scores table on game page shows dmg taken instead of xp contribution

### ISSUE THREAD

**Issue by jgonzalezn** [Heroes-Profile/heroesprofile#737]
**Describe the bug**
The match scores table shows columns "damage taken" and "xp contribution", but both columns show the same value (dmg taken) in both columns.

**To Reproduce**
1. Open any match details
2. Scroll to match score table

**Expected behavior**
XP contribution has the actual XP contribution value instead of repeating the dmg taken value.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Macos 14.2.1
 - Chrome 121.0.6167.139

**Comment by Zemill** [comment]
Good catch, fixing now
