### ISSUE TITLE
Thousands Separator

### ISSUE THREAD

**Issue by Elitesparkle** [Heroes-Profile/heroesprofile#741]
The site rewrite is incorrectly using `.` rather than `,` as a thousands separator.

**Comment by Zemill** [comment]
Can you provide an example, what page?

![image](https://github.com/Heroes-Profile/heroesprofile/assets/33404722/e8a07585-36a8-494b-9afa-5c4cc287d986)


Seems fine

**Comment by Elitesparkle** [comment]
That's the page, but it looks different on my end.

![image](https://github.com/Heroes-Profile/heroesprofile/assets/9367799/27289b65-6986-409c-b6d6-0e3b1c4dd33f)

**Comment by Zemill** [comment]
Ok, something I wasn't exactly aware of.  We are using a built in function to convert numbers with the separators...this function apparently takes into account the standard number scheme in your physical location.


ChatGPT says

const number = 1234567.89;

// Using default locale (usually the user's browser locale)
const defaultFormatted = number.toLocaleString();
console.log(defaultFormatted);
// Output: "1,234,567.89" (formatted according to the default locale)

// Using a specific locale (e.g., en-US for U.S. English)
const usFormatted = number.toLocaleString('en-US');
console.log(usFormatted);
// Output: "1,234,567.89" (formatted according to U.S. English locale)

// Using a different locale (e.g., de-DE for German)
const germanFormatted = number.toLocaleString('de-DE');
console.log(germanFormatted);
// Output: "1.234.567,89" (formatted according to German locale)



This seems like it would work well, except it isnt clear to me how confusing it is to someone who lives with the period being the delimiter.  For example...  win rate of 56.70 and games played of 46.034....do you just know the games played is a thousands item?  

Whats the standard way of interpreting in countries that use periods, if you know

**Comment by Zemill** [comment]
Ok that makes sense.  I didn't add that function to columns like win rate as I knew it didn't need the delimit formatting, not realizing it would use a users local to modify it to a comma or period.  So I will likely make it consistent and do the comma across the site
