### ISSUE TITLE
Remove Button for Player Profile Search

### ISSUE THREAD

**Issue by Elitesparkle** [Heroes-Profile/heroesprofile#742]
The site rewrite doesn't have a button to remove a recently searched player from the dedicated bar.

**Comment by Zemill** [comment]
Good point

**Comment by Zemill** [comment]
@lifeinabstract I have added this, need remove button styled similar to live site

https://github.com/Heroes-Profile/heroesprofile/blob/28580b966a34dea89e40f70d565a710507ad6bf1/resources/views/nav.blade.php#L163

https://github.com/Heroes-Profile/heroesprofile/blob/develop/resources/js/components/RemoveBattletagNav.vue


Live site
![image](https://github.com/Heroes-Profile/heroesprofile/assets/33404722/da5facff-0516-4b9e-a316-9b38bc9e182f)


rewrite
![image](https://github.com/Heroes-Profile/heroesprofile/assets/33404722/97834b43-02fb-4a11-8252-34a70602a7e9)
