### ISSUE TITLE
Missing Filter Button for Player Profile

### ISSUE THREAD

**Issue by Elitesparkle** [Heroes-Profile/heroesprofile#807]
There is no Filter button in the Player Profile page.

![image](https://github.com/Heroes-Profile/heroesprofile/assets/9367799/d44b7aaa-4573-4d0c-a28d-49e8552b391d)

**Comment by Zemill** [comment]
This page has no filter button, data changes when filters change.  Are you looking for some information to make that behavior more apparent?  There are not too many situations on the site where filtering behaves this way, so I suppose we could change that.

let me know your thoughts

**Comment by Elitesparkle** [comment]
> Are you looking for some information to make that behavior more apparent?

No, it's easy to notice how it works.

> This page has no filter button, data changes when filters change.

When the user wants to use both filters (eg. Storm League, 2024 Season 1), the site loads an intermediate page (eg. Storm League, All Seasons) that is not needed, wasting time and resources.

> There are not too many situations on the site where filtering behaves this way, so I suppose we could change that.

I also find it inconsistent with the rest of the site.
