### ISSUE TITLE
Show BattleTag in Site Settings

### ISSUE THREAD

**Issue by Elitesparkle** [Heroes-Profile/heroesprofile#811]
If a user has multiple accounts with the same name, there is no way to tell which account is logged in.

I think it would be nice to show the BattleTag in Site Settings.

**Comment by Elitesparkle** [comment]
I'm not supposed to see your nickname instead of mine when logging in.

![image](https://github.com/Heroes-Profile/heroesprofile/assets/9367799/be7e4d5b-e474-4e89-9e9e-4fe5c7a3bfaf)

**Comment by Zemill** [comment]
I think this is fixed now
