### ISSUE TITLE
heroesprofile.com is not working this morning

### ISSUE THREAD

**Issue by jds3d** [Heroes-Profile/heroesprofile#821]
**Describe the bug**

1. The site is loading intermittently
2. I am seeing :8000 occasionally after the url.
3. when it did load, the heroes section of the profile doesn't have hero MMR anymore.

**To Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Zemill** [comment]
We are swapping over from the old site to the new site.  Ran into some issues we are working on

**Comment by jds3d** [comment]
i don't want to bother you while you're working on it, but do you have an ETA for the fixes?  also, if what i saw of the new site is accurate, i'm not sure it has all of the features of the old site and i'm wondering if it will be possible for users to switch back and forth.

and lastly, do you need any help?  I am something of a software developer myself.

**Comment by Zemill** [comment]
> i don't want to bother you while you're working on it, but do you have an ETA for the fixes? also, if what i saw of the new site is accurate, i'm not sure it has all of the features of the old site and i'm wondering if it will be possible for users to switch back and forth.
> 


It is not currently possible to swap between sites.

> and lastly, do you need any help? I am something of a software developer myself.
I believe the remaining issues has to do with the redirection of https://heroesprofile.com/ to https://www.heroesprofile.com/


https://www.heroesprofile.com/ appears to be working fine right now

**Comment by jds3d** [comment]
then my last question is around bullet 3, for example, on 
https://www.heroesprofile.com/Player/Orion/3917412/1/Hero
is it possible to see his heroes sorted by MMR?  I don't see that option in the column list, but it was one of the default columns in the old version.

**Comment by Zemill** [comment]
> then my last question is around bullet 3, for example, on https://www.heroesprofile.com/Player/Orion/3917412/1/Hero is it possible to see his heroes sorted by MMR? I don't see that option in the column list, but it was one of the default columns in the old version.

I will work on it in a bit once I fix the server issue

**Comment by Zemill** [comment]
I think I have fixed the server configuration.  Let me know if you see any issues with it

**Comment by Zemill** [comment]
> then my last question is around bullet 3, for example, on https://www.heroesprofile.com/Player/Orion/3917412/1/Hero is it possible to see his heroes sorted by MMR? I don't see that option in the column list, but it was one of the default columns in the old version.

This has been added for the hero all page, still need to do it for Role, but you were asking after hero
