### ISSUE TITLE
Player MMR did not update for one player in one uploaded match 

### ISSUE THREAD

**Issue by becnelli** [Heroes-Profile/heroesprofile#834]
**Describe the bug**

**To Reproduce**
1. Go to https://www.heroesprofile.com/Player/becnelli/9936431/1
2. Scroll down to [Blackheart's Bay|Quick Match|02/24/2024 3:58:14 pm](https://www.heroesprofile.com/Match/Single/52283717) match
3. Notice that the stats still show default values before calculations are performed (e.g., PLAYER MMR 1,800, CHANGE 0.00, HERO MMR 1,800, CHANGE 0.00, ROLE MMR 1,800, CHANGE 0.00) << BUG
4. Notice that future games are calculated and displayed correctly

**Expected behavior**
The Player/Hero/Role MMRs are updated based on the game data. 

**Screenshots**
![image](https://github.com/Heroes-Profile/heroesprofile/assets/1691012/f90036ec-6e1c-445e-a2dd-9ba1b1431aad)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Uploads for other players is accurate.

**Comment by Zemill** [comment]
Caused by caching profile page data before MMR had ran.  I know how to fix it, shouldn't be too bad.  

Will get to it in the next update.   If you look at the match page for this game you can see the MMR data was calculated.  

Thanks
Zemill
