### ISSUE TITLE
Drafter broken

### ISSUE THREAD

**Issue by VirtueAvatar** [Heroes-Profile/heroesprofile#840]
**Describe the bug**
The drafter tool doesn't load properly.

**To Reproduce**
1. Go to Tools
2. Go to Drafter
3. Click Start Draft 

**Expected behavior**
I don't know, I haven't used this before. Looking for good ally/counter picks in draft.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi
 - Version 6.5.3206.63 (Stable channel) (64-bit)

**Additional context**
The page doesn't load properly at all

**Comment by Zemill** [comment]
Resolved
