### ISSUE TITLE
Link in the menu located at Tools=>Game Data leads to broken website

### ISSUE THREAD

**Issue by vghougassian** [Heroes-Profile/heroesprofile#867]
**Describe the bug**
Sorry, this is the real last request for today, just because it's a broken link.

**To Reproduce**
Hover over the Tools label in the top navigation menu and click on the Game Data link on the dropdown.  Link sends the user to the dev.heroesprofile.com subdomain which throws a DNS error.

**Expected behavior**
The link goes to a working website.

**Screenshots**
![image](https://github.com/Heroes-Profile/heroesprofile/assets/116777453/3bdc1af0-e524-429f-bcbd-72f18c3cb648)

**Comment by Zemill** [comment]
Thanks, I removed this website.

It will be removed in the next 5min
