### ISSUE TITLE
Docker Setup Failing

### ISSUE THREAD

**Issue by Zemill** [Heroes-Profile/heroesprofile#87]
The automatic docker setup is failing.  Appears to be cause by a root level access issue.

2020-03-06T13:42:02.277912Z 4 [Note] Access denied for user 'root'@'172.18.0.1' (using password: NO)

The .env file that is auto generated by the script sets the docker password to docker,  but that error suggests no password is being used by docker/laravel to access the DB.

**Comment by Gibbo3771** [comment]
@Zemill I had a look at the compose file and would like to tackle this issue, can I be assigned? Cheers.

**Comment by Gibbo3771** [comment]
PR up #93

**Comment by Zemill** [comment]
Resolved in PR#93
