### ISSUE TITLE
Talent Builder is slow

### ISSUE THREAD

**Issue by HenrikRaz** [Heroes-Profile/heroesprofile#880]
**Describe the bug**
The Talent Builder is very slow.

**To Reproduce**
1. Go to https://www.heroesprofile.com/Global/Talents/Builder/Imperius?timeframe_type=major&timeframe=2.55&game_type=sl&region=EU&league_tier=Diamond,Master&hero_league_tier=Master,Diamond&mirror=0
2. Click on the talents
3. it now takes a lot of time to load. Much more than on the old site.

**Expected behavior**
Should be crisp and fast please :)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by Zemill** [comment]
So I loaded up the legacy site in my local environment and also loaded the current site in dev and ran some tests.

They were almost exactly the same.  Sometimes legacy would load a little faster, sometimes the new site would.  Sometimes the legacy site would take twice as long, sometimes the new site would take twice as long.

I tried it with multiple filter sets, including the on you provided, and its the same result.  Not sure how to proceed at this point

**Comment by Zemill** [comment]
I will do some more testing on this as well.  In my local environment caching is off, so I would have expected to see the maximum time it takes for any request...I suppose its possible caching is causing issues, so I will investigate that as well

**Comment by HenrikRaz** [comment]
![image](https://github.com/Heroes-Profile/heroesprofile/assets/20615795/c7c2965d-e693-4db2-98f9-049d9bd0ef69)

I've never had the old Talent Builder "load" for more than a second or two. It's very strange.

**Comment by Zemill** [comment]
I did find something odd unrelated to caching I am looking into

**Comment by Zemill** [comment]
I think the thing causing the talent builder to take so long to load is the section for displaying specific replays that match the build.

I am putting in a database change to hopefully resolve it, but if it doesnt, I will disable this section until I can put in a permanent fix

**Comment by HenrikRaz** [comment]
Much faster with Abathur as u mention, so the Caching seems like part of the issue. Thanks!

**Comment by Zemill** [comment]
I removed the list of replays that are shown after the builder.  It increased the builder speed significantly in my opinion.  Please let me know your thoughts.

I will look to put this back in with more testing

**Comment by HenrikRaz** [comment]
It already seems faster. Would love to see the replays again in the future, as I personally watch those to see if I can find any particularly strong playstyle or tricks with the builds.
