### ISSUE TITLE
Filters resetting when clicking on a Hero's profile on GLOBAL HERO STATISTICS page

### ISSUE THREAD

**Issue by nick2202** [Heroes-Profile/heroesprofile#908]
**Describe the bug**
When on Global Hero Stats page and clicking on a Hero, all filters reset when it directs you to that Hero's page

**To Reproduce**
1. Go to https://www.heroesprofile.com/Global/Hero 
2. Set some filters (e.g. https://www.heroesprofile.com/Global/Hero?timeframe_type=minor&timeframe=2.55.4.91769,2.55.4.91418&game_type=sl,qm&region=NA,EU,KR,CN&league_tier=Master,Diamond,Platinum,Gold&statfilter=win_rate&build_type=Popular&mirror=0)
3. Click on any Hero.
4. URL will be e.g. https://www.heroesprofile.com/Global/Talents/Rehgar instad of https://www.heroesprofile.com/Global/Talents/Rehgar?timeframe_type=minor&timeframe=2.55.4.91769,2.55.4.91418&game_type=sl,qm&region=NA,EU,KR,CN&league_tier=Master,Diamond,Platinum,Gold&statfilter=win_rate&build_type=Popular&mirror=0

**Expected behavior**
FIlters should stay

**Comment by Zemill** [comment]
So I briefly tested this.  

This is what I found:
When a user sets their filters manually, then navigating to the talents page accurately pulls through their filters choices.

If a user instead navigates to a page with a url that has preset filters, then the urls are not set when navigating to the hero page.

So a url like  https://www.heroesprofile.com/Global/Hero?timeframe_type=minor&timeframe=2.55.4.91769,2.55.4.91418&game_type=sl,qm&region=NA,EU,KR,CN&league_tier=Master,Diamond,Platinum,Gold&statfilter=win_rate&build_type=Popular&mirror=0 when clicked from here, presents the issue, but if I were to go to https://www.heroesprofile.com/ and manually set those filter options, it would work

**Comment by nick2202** [comment]
Ah, interesting.
Maybe that's why it never worked for me, I had it happen a few times, then just copied the part of the URL with the params to my clipboard manager and looked them up whenever I needed them :D
